2018-12-17 19:16:13.496 [error] <0.226.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {badkey,connection} in 'Elixir.Logs.Subscriber':init_connection/1 line 27 in context start_error
2018-12-17 19:16:13.496 [error] <0.224.0> CRASH REPORT Process <0.224.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logs.Subscriber',{{badkey,connection},[{'Elixir.Logs.Subscriber',init_connection,1,[{file,"lib/logs/subscriber.ex"},{line,27}]},{'Elixir.Logs.Subscriber',init,1,[{file,"lib/logs/subscriber.ex"},{line,14}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},{'Elixir.Logs.Application',start,[normal,[]]}} in application_master:init/4 line 138
2018-12-17 19:17:06.850 [error] <0.226.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {badkey,connection} in 'Elixir.Logs.Subscriber':init_connection/1 line 27 in context start_error
2018-12-17 19:17:06.850 [error] <0.224.0> CRASH REPORT Process <0.224.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Logs.Subscriber',{{badkey,connection},[{'Elixir.Logs.Subscriber',init_connection,1,[{file,"lib/logs/subscriber.ex"},{line,27}]},{'Elixir.Logs.Subscriber',init,1,[{file,"lib/logs/subscriber.ex"},{line,14}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},{'Elixir.Logs.Application',start,[normal,[]]}} in application_master:init/4 line 138
2018-12-17 19:19:38.714 [error] <0.227.0> CRASH REPORT Process <0.227.0> with 0 neighbours crashed with reason: {badkey,connection} in 'Elixir.Logs.Subscriber':init_connection/1 line 27
2018-12-17 19:19:38.714 [error] <0.226.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {badkey,connection} in 'Elixir.Logs.Subscriber':init_connection/1 line 27 in context start_error
2018-12-17 19:21:19.328 [error] <0.227.0>@Elixir.AMQP.Channel:open:15 CRASH REPORT Process <0.227.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.AMQP.Channel':open(<<"connection">>) line 15
2018-12-17 19:21:19.328 [error] <0.226.0>@Elixir.AMQP.Channel:open:15 Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason no function clause matching 'Elixir.AMQP.Channel':open(<<"connection">>) line 15 in context start_error
2018-12-17 19:22:14.994 [error] <0.226.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'rabbits' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.241.0>,{call,{'exchange.declare',0,<<"rabbits">>,<<"topic">>,false,false,false,false,false,[]},none,<0.227.0>},60000]}} in context start_error
2018-12-17 19:23:40.081 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'rabbits' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.232.0>,{call,{'exchange.declare',0,<<"rabbits">>,<<"topic">>,false,false,false,false,false,[]},none,<0.218.0>},60000]}} in gen_server:call/3 line 223
2018-12-17 19:23:40.081 [error] <0.217.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'rabbits' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.232.0>,{call,{'exchange.declare',0,<<"rabbits">>,<<"topic">>,false,false,false,false,false,[]},none,<0.218.0>},60000]}} in context start_error
2018-12-17 19:24:51.569 [error] <0.218.0> CRASH REPORT Process <0.218.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'rabbits' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.232.0>,{call,{'exchange.declare',0,<<"rabbits">>,<<"topic">>,false,false,false,false,false,[]},none,<0.218.0>},60000]}} in gen_server:call/3 line 223
2018-12-17 19:24:51.569 [error] <0.217.0> Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'rabbits' in vhost '/': received 'false' but current is 'true'">>}},{gen_server,call,[<0.232.0>,{call,{'exchange.declare',0,<<"rabbits">>,<<"topic">>,false,false,false,false,false,[]},none,<0.218.0>},60000]}} in context start_error
2018-12-17 19:27:27.906 [error] <0.227.0> 'Elixir.Logs.Subscriber' 'Elixir.Logs.Subscriber' received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-zEQ5FVvYAk4ybgaxth2HpA">>}}
2018-12-17 19:29:54.020 [error] <0.227.0>@Elixir.Logs.Subscriber:handle_info:46 gen_server 'Elixir.Logs.Subscriber' terminated with reason: no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"{\"id\":2,\"commodity\":\"Pen\",\"quantity\":\"10\",\"location\":\"Office\",\"delivery_id\":null...">>,...}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46
2018-12-17 19:29:54.028 [error] <0.227.0>@Elixir.Logs.Subscriber:handle_info:46 CRASH REPORT Process 'Elixir.Logs.Subscriber' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"{\"id\":2,\"commodity\":\"Pen\",\"quantity\":\"10\",\"location\":\"Office\",\"delivery_id\":null...">>,...}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46
2018-12-17 19:29:54.028 [error] <0.226.0>@Elixir.Logs.Subscriber:handle_info:46 Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at <0.227.0> exit with reason no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"{\"id\":2,\"commodity\":\"Pen\",\"quantity\":\"10\",\"location\":\"Office\",\"delivery_id\":null...">>,...}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46 in context child_terminated
2018-12-17 19:29:59.052 [error] <0.244.0>@Elixir.Logs.Subscriber:handle_info:46 gen_server 'Elixir.Logs.Subscriber' terminated with reason: no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"[2]">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.cta...">>,...}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46
2018-12-17 19:29:59.054 [error] <0.244.0>@Elixir.Logs.Subscriber:handle_info:46 CRASH REPORT Process 'Elixir.Logs.Subscriber' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"[2]">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.cta...">>,...}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46
2018-12-17 19:29:59.054 [error] <0.226.0>@Elixir.Logs.Subscriber:handle_info:46 Supervisor 'Elixir.Logs.Supervisor' had child 'Elixir.Logs.Subscriber' started with 'Elixir.Logs.Subscriber':start_link([]) at <0.244.0> exit with reason no function clause matching 'Elixir.Logs.Subscriber':handle_info({basic_deliver,<<"[2]">>,#{app_id => undefined,cluster_id => undefined,consumer_tag => <<"amq.cta...">>,...}}, #{channel => #{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',...},...},...}) line 46 in context child_terminated
